# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
    - go build -C . -o ./bin
  build-r:
    cmds:
    - go build -C . -o ./bin -ldflags "-s -w"
  rich-test:
    cmds:
    - go test -v -json ./... | go run github.com/mfridman/tparse@latest -all
