name: tests

# This is seperate becouse it's not related the reales of new versions
# and I want to keep test results separate from bulding and releasing the app.

on:
    push:
      branches: [ "main" ] # Triggers on pushes to main
      tags: [ "v*" ] # Triggers on any tag with the prefix 'v'
    pull_request:
      branches: [ "main" ] # Triggers on pull requests

# My original test solution
# jobs:
#   tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1

#       - name: Run tests and generate test report
#         run: |
#           go test -v -json ./... | go run github.com/mfridman/tparse@latest -all
#         continue-on-error: true

# The gotestfmt solution
jobs:
  test:
    name: Format log output
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.5

      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run go test
        run: |
          set -euo pipefail
          go test -json -p 1 -v ./... 2>&1 | tee /tmp/gotest.log
          
      - name: Format log output
        run: |
          set -euo pipefail
          cat /tmp/gotest.log | gotestfmt
